[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ml-from-scratch"
version = "0.1.0"
description = "ML models implemented from scratch"
dependencies = [
    "numpy",
    "pandas"
]
